language: node_js
node_js:
    - 10.21.0
cache:
    yarn: true
before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
    - export PATH="$HOME/.yarn/bin:$PATH"
    - openssl aes-256-cbc -K $encrypted_9b6c99d9f0dc_key -iv $encrypted_9b6c99d9f0dc_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host www.wuliang.me\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
    - yarn run docs:build
after_success:
    - scp -rp ./dist/* wuliang@sh1.wuliang.me:/home/wuliang/any-proxy/html/www.wuliang.me
