language: node_js
node_js:
- 12.18.3
cache:
  yarn: true
before_install:
- openssl aes-256-cbc -K $encrypted_9b2d7e19d83c_key -iv $encrypted_9b2d7e19d83c_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host hk1.wuliang.me\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- yarn run docs:build
after_success:
- scp -rp ./dist/* root@hk1.wuliang.me:/opt/html/www.wuliang.me
