language: node_js
node_js:
- 12.18.3
cache:
  yarn: true
script:
- yarn run docs:build
- sed -s -i 's#present wuliang142857#present wuliang142857 <div><a href="https://beian.miit.gov.cn">&#27993;&#73;&#67;&#80;&#22791;&#49;&#55;&#48;&#53;&#53;&#55;&#56;&#55;&#21495;&#45;&#49;</a></div>#g' dist/index.html
after_success:
- curl -LO https://gosspublic.alicdn.com/ossutil/1.7.1/ossutil64
- chmod a+x ossutil64
- ./ossutil64 --endpoint=$OSS_ENDPOINT --access-key-id=$OSS_ACCESS_KEY_ID --access-key-secret=$OSS_ACCESS_KEY_SECRET cp -r -f dist/ oss://$OSS_BUCKET_NAME/
