name: 自动部署
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v3
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
          
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
          
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      - name: Install dependencies
        run: pnpm install
        
      - name: Build
        run: pnpm run docs:build
        
      - run: curl -LO https://gosspublic.alicdn.com/ossutil/1.7.7/ossutil64
      - run: chmod a+x ossutil64
      - run: ./ossutil64 --endpoint=oss-cn-shanghai.aliyuncs.com --access-key-id=${{ secrets.OSS_ACCESS_KEY_ID }} --access-key-secret=${{ secrets.OSS_ACCESS_KEY_SECRET }} cp -r -f dist/ oss://${{ secrets.OSS_BUCKET_NAME }}/
