name: 自动部署
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn run build
      - run: curl -LO https://gosspublic.alicdn.com/ossutil/1.7.1/ossutil64
      - run: chmod a+x ossutil64
      - shell: bash
        with:
          OSS_ENDPOINT: ${{ secrets.OSS_ENDPOINT }}
          OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          OSS_BUCKET_NAME: ${{ secrets.OSS_BUCKET_NAME }}
        run: ./ossutil64 --endpoint=${{ SUPER_SECRET }} --access-key-id=${{ OSS_ACCESS_KEY_ID }} --access-key-secret=${{ OSS_ACCESS_KEY_SECRET }} cp -r -f dist/ oss://${{ OSS_BUCKET_NAME }}/
