name: 自动部署
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn run build
      - run: curl -LO https://gosspublic.alicdn.com/ossutil/1.7.7/ossutil64
      - run: chmod a+x ossutil64
      - run: ./ossutil64 --endpoint=${{ secrets.OSS_ENDPOINT }} --access-key-id=${{ secrets.OSS_ACCESS_KEY_ID }} --access-key-secret=${{ secrets.OSS_ACCESS_KEY_SECRET }} cp -r -f dist/ oss://${{ secrets.OSS_BUCKET_NAME }}/
